before_script:
- composer install
- touch test.sqlite

test:app:
  script:
  - DB_DATABASE=$PWD"/test.sqlite" ./vendor/bin/phpunit --coverage-html coverage --coverage-clover coverage/clover.xml --configuration phpunit.xml || FAILURE=1
  - ./vendor/bin/php-coverage-badger coverage/clover.xml coverage/coverage.svg
  - (exit $FAILURE)
  artifacts:
    paths:
    - coverage
