before_script:
- composer install
- cp schema/propel.php.dev.dist schema/propel.php;
- (cd schema; ../vendor/bin/propel model:build; ../vendor/bin/propel sql:insert; ../vendor/bin/propel migrate)
- composer dump-autoload

test:app:
  script:
  - ./vendor/bin/phpunit test --coverage-html coverage --coverage-clover coverage/clover.xml --configuration phpunit.xml || FAILURE=1
  - ./vendor/bin/php-coverage-badger coverage/clover.xml coverage/coverage.svg
  - (exit $FAILURE)
  artifacts:
    paths:
    - coverage
